export const data = [
    { id: 1, name: "Arsenal", isTest: false },
    { id: 2, name: "Arsenal Kyiv 2019", isTest: false },
    { id: 3, name: "1) Manchester City 2) Arsenal", isTest: false },
    { id: 4, name: "3 or more of Chelsea, Leeds, Southampton & Arsenal to score 2 or more goals", isTest: false },
    { id: 5, name: "3 or more of Chelsea, Leeds, Southampton & Arsenal to win", isTest: false },
    { id: 6, name: "3 or more of Man Utd, Arsenal, Chelsea & Leeds to score 2 or more", isTest: false },
    { id: 7, name: "3 or more of Man Utd, Arsenal, Chelsea & Leeds to win", isTest: false },
    { id: 8, name: "Aiyegbeni Yakubi (Arsenal)", isTest: false },
    { id: 9, name: "Aiyegbeni Yakubi (Arsenal) (EngPre)", isTest: false },
    { id: 10, name: "Ajax Vs Arsenal", isTest: false },
    { id: 11, name: "Alexander Hleb (Arsenal)", isTest: false },
    { id: 12, name: "Arizona Arsenal SC [W]", isTest: false },
    { id: 13, name: "Arsenal", isTest: false },
    { id: 14, name: "Arsenal", isTest: false },
    { id: 15, name: "Arsenal", isTest: false },
    { id: 16, name: "Arsenal (1st half)", isTest: false },
    { id: 17, name: "Arsenal 2nd Penalty - Goal", isTest: false },
    { id: 18, name: "Arsenal 2nd Penalty - No Goal", isTest: false },
]