import { SvgIconTypeMap } from "@mui/material"
import { OverridableComponent } from "@mui/material/OverridableComponent"

import { AccessTime, AccountBalance, AccountCircle, Add, AddCircle, AddCircleOutline, AddPhotoAlternate, AddHome, AddLink, AlignVerticalBottom, Apps, ArrowBackIosNew, ArrowCircleDown, ArrowCircleUp, ArrowBack, ArrowForward, ArrowForwardIos, ArrowUpward, ArrowDownward, Article, AspectRatio, Assessment, Assignment, AssignmentInd, AssignmentLate, AssignmentTurnedIn, AssuredWorkload, AttachEmail, Attribution, Attachment, AttachFile, AutoDelete, AutoStories, Autorenew, Backup, Badge, BackupTable, Balcony, Ballot, BarChart, Beenhere, Blinds, BlindsClosed, Block, Bolt, BookmarkAdd, BookmarkAdded, BookmarkRemove, BookmarkBorder, Bookmark, Bookmarks, BorderAll, BorderColor, Boy, BrowserUpdated, Brush, BuildCircle, Build, BurstMode, Cached, CalendarMonth, CalendarToday, CalendarViewDay, CalendarViewMonth, CalendarViewWeek, Cancel, CancelPresentation, CenterFocusStrong, CenterFocusWeak, Chair, ChangeCircle, Chat, ChatBubble, ChatBubbleOutline, Check, CheckBox, CheckBoxOutlineBlank, CheckCircle, CheckCircleOutline, ChevronLeft, ChevronRight, ChromeReaderMode, CleaningServices, Clear, Close, ClearAll, CloudDone, CloudDownload, CloudUpload, Collections, CollectionsBookmark, ColorLens, Colorize, Comment, CommentBank, CommentsDisabled, Commit, CompareArrows, Compress, Computer, CompassCalibration, ContactEmergency, ContactMail, ContactPage, ContactSupport, Contacts, ContentCopy, ContentPaste, ContentPasteGo, ContentPasteOff, ContentPasteSearch, ControlPoint, Cookie, CopyAll, CorporateFare, Create, CreateNewFolder, CropFree, CropOriginal, Dashboard, DashboardCustomize, DataSaverOff, DataSaverOn, Dataset, DatasetLinked, DateRange } from "@mui/icons-material"

type IconType = {
    name: string
    component: OverridableComponent<SvgIconTypeMap<{}, "svg">> & {
        muiName: string
    }

}

export const icons: IconType[] = [
    {
        name: "AccountCircle",
        component: AccountCircle
    }, {
        name: "AutoStories",
        component: AutoStories
    }, {
        name: "ChromeReaderMode",
        component: ChromeReaderMode
    }, {
        name: "Bookmark",
        component: Bookmark
    }, {
        name: "BookmarkAdd",
        component: BookmarkAdd
    }, {
        name: "BookmarkAdded",
        component: BookmarkAdded
    }, {
        name: "BookmarkRemove",
        component: BookmarkRemove
    }, {
        name: "Bookmarks",
        component: Bookmarks
    }, {
        name: "BookmarkBorder",
        component: BookmarkBorder
    }, {
        name: "AccountBalance",
        component: AccountBalance
    }, {
        name: "AssuredWorkload",
        component: AssuredWorkload
    }, {
        name: "AddHome",
        component: AddHome
    }, {
        name: "Balcony",
        component: Balcony
    }, {
        name: "Blinds",
        component: Blinds
    }, {
        name: "BlindsClosed",
        component: BlindsClosed
    }, {
        name: "ClearAll",
        component: ClearAll
    }, {
        name: "AccessTime",
        component: AccessTime
    }, {
        name: "Attribution",
        component: Attribution
    }, {
        name: "Boy",
        component: Boy
    }, {
        name: "BorderColor",
        component: BorderColor
    }, {
        name: "Create",
        component: Create
    }, {
        name: "Add",
        component: Add
    }, {
        name: "AddCircle",
        component: AddCircle
    }, {
        name: "ControlPoint",
        component: ControlPoint
    }, {
        name: "AddCircleOutline",
        component: AddCircleOutline
    }, {
        name: "AutoDelete",
        component: AutoDelete
    }, {
        name: "BurstMode",
        component: BurstMode
    }, {
        name: "AddPhotoAlternate",
        component: AddPhotoAlternate
    }, {
        name: "Collections",
        component: Collections
    }, {
        name: "CollectionsBookmark",
        component: CollectionsBookmark
    }, {
        name: "AssignmentInd",
        component: AssignmentInd
    }, {
        name: "Badge",
        component: Badge
    }, {
        name: "AssignmentLate",
        component: AssignmentLate
    }, {
        name: "AssignmentTurnedIn",
        component: AssignmentTurnedIn
    }, {
        name: "AddLink",
        component: AddLink
    }, {
        name: "Attachment",
        component: Attachment
    }, {
        name: "AttachFile",
        component: AttachFile
    }, {
        name: "AttachEmail",
        component: AttachEmail
    }, {
        name: "AlignVerticalBottom",
        component: AlignVerticalBottom
    }, {
        name: "BarChart",
        component: BarChart
    }, {
        name: "Assessment",
        component: Assessment
    }, {
        name: "BackupTable",
        component: BackupTable
    }, {
        name: "BorderAll",
        component: BorderAll
    }, {
        name: "Apps",
        component: Apps
    }, {
        name: "Ballot",
        component: Ballot
    }, {
        name: "ArrowBackIosNew",
        component: ArrowBackIosNew
    }, {
        name: "ArrowForwardIos",
        component: ArrowForwardIos
    }, {
        name: "ChevronLeft",
        component: ChevronLeft
    }, {
        name: "ChevronRight",
        component: ChevronRight
    }, {
        name: "ArrowCircleDown",
        component: ArrowCircleDown
    }, {
        name: "ArrowCircleUp",
        component: ArrowCircleUp
    }, {
        name: "ArrowBack",
        component: ArrowBack
    }, {
        name: "ArrowForward",
        component: ArrowForward
    }, {
        name: "ArrowUpward",
        component: ArrowUpward
    }, {
        name: "ArrowDownward",
        component: ArrowDownward
    }, {
        name: "CompareArrows",
        component: CompareArrows
    }, {
        name: "Assignment",
        component: Assignment
    }, {
        name: "Article",
        component: Article
    }, {
        name: "AspectRatio",
        component: AspectRatio
    }, {
        name: "Autorenew",
        component: Autorenew
    }, {
        name: "Cached",
        component: Cached
    }, {
        name: "ChangeCircle",
        component: ChangeCircle
    }, {
        name: "Backup",
        component: Backup
    }, {
        name: "CloudDone",
        component: CloudDone
    }, {
        name: "CloudDownload",
        component: CloudDownload
    }, {
        name: "CloudUpload",
        component: CloudUpload
    }, {
        name: "Beenhere",
        component: Beenhere
    }, {
        name: "Block",
        component: Block
    }, {
        name: "Bolt",
        component: Bolt
    }, {
        name: "BrowserUpdated",
        component: BrowserUpdated
    }, {
        name: "Brush",
        component: Brush
    }, {
        name: "BuildCircle",
        component: BuildCircle
    }, {
        name: "Build",
        component: Build
    }, {
        name: "Cancel",
        component: Cancel
    }, {
        name: "DateRange",
        component: DateRange
    }, {
        name: "CalendarMonth",
        component: CalendarMonth
    }, {
        name: "CalendarToday",
        component: CalendarToday
    }, {
        name: "CalendarViewDay",
        component: CalendarViewDay
    }, {
        name: "CalendarViewMonth",
        component: CalendarViewMonth
    }, {
        name: "CalendarViewWeek",
        component: CalendarViewWeek
    }, {
        name: "CancelPresentation",
        component: CancelPresentation
    }, {
        name: "CenterFocusStrong",
        component: CenterFocusStrong
    }, {
        name: "CenterFocusWeak",
        component: CenterFocusWeak
    }, {
        name: "Chair",
        component: Chair
    }, {
        name: "CommentBank",
        component: CommentBank
    }, {
        name: "Chat",
        component: Chat
    }, {
        name: "Comment",
        component: Comment
    }, {
        name: "CommentsDisabled",
        component: CommentsDisabled
    }, {
        name: "ChatBubble",
        component: ChatBubble
    }, {
        name: "ChatBubbleOutline",
        component: ChatBubbleOutline
    }, {
        name: "Check",
        component: Check
    }, {
        name: "CheckBox",
        component: CheckBox
    }, {
        name: "CheckBoxOutlineBlank",
        component: CheckBoxOutlineBlank
    }, {
        name: "CheckCircle",
        component: CheckCircle
    }, {
        name: "CheckCircleOutline",
        component: CheckCircleOutline
    }, {
        name: "CleaningServices",
        component: CleaningServices
    }, {
        name: "Clear",
        component: Clear
    }, {
        name: "Close",
        component: Close
    }, {
        name: "ColorLens",
        component: ColorLens
    }, {
        name: "Colorize",
        component: Colorize
    }, {
        name: "Commit",
        component: Commit
    }, {
        name: "Compress",
        component: Compress
    }, {
        name: "Computer",
        component: Computer
    }, {
        name: "CompassCalibration",
        component: CompassCalibration
    }, {
        name: "ContactEmergency",
        component: ContactEmergency
    }, {
        name: "ContactMail",
        component: ContactMail
    }, {
        name: "ContactPage",
        component: ContactPage
    }, {
        name: "ContactSupport",
        component: ContactSupport
    }, {
        name: "Contacts",
        component: Contacts
    }, {
        name: "ContentCopy",
        component: ContentCopy
    }, {
        name: "ContentPaste",
        component: ContentPaste
    }, {
        name: "ContentPasteGo",
        component: ContentPasteGo
    }, {
        name: "ContentPasteOff",
        component: ContentPasteOff
    }, {
        name: "ContentPasteSearch",
        component: ContentPasteSearch
    }, {
        name: "Cookie",
        component: Cookie
    }, {
        name: "CopyAll",
        component: CopyAll
    }, {
        name: "CorporateFare",
        component: CorporateFare
    }, {
        name: "CreateNewFolder",
        component: CreateNewFolder
    }, {
        name: "CropFree",
        component: CropFree
    }, {
        name: "CropOriginal",
        component: CropOriginal
    }, {
        name: "Dashboard",
        component: Dashboard
    }, {
        name: "DashboardCustomize",
        component: DashboardCustomize
    }, {
        name: "DataSaverOff",
        component: DataSaverOff
    }, {
        name: "DataSaverOn",
        component: DataSaverOn
    }, {
        name: "Dataset",
        component: Dataset
    }, {
        name: "DatasetLinked",
        component: DatasetLinked
    },
]

export * as mui from "@mui/material"
export * as muiIcons from "@mui/icons-material"